/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-family-base)', 'sans-serif'],
      },
      fontWeight: {
        regular: 'var(--font-weight-regular)',
        medium: 'var(--font-weight-medium)',
        bold: 'var(--font-weight-bold)',
      },
      fontSize: {
        'title-xxl': 'var(--font-size-title-xxlarge)',
        'title-l': 'var(--font-size-title-large)',
        'title-m': 'var(--font-size-title-medium)',
        'title-s': 'var(--font-size-title-small)',
        'body-l': 'var(--font-size-body-large)',
        'body-m': 'var(--font-size-body-medium)',
        'body-s': 'var(--font-size-body-small)',
        'label-xl': 'var(--font-size-label-xlarge)',
        'label-l': 'var(--font-size-label-large)',
        'label-m': 'var(--font-size-label-medium)',
        'label-s': 'var(--font-size-label-small)',
      },
      letterSpacing: {
        base: 'var(--letter-spacing-base)',
      },
      spacing: {
        '0': 'var(--spacing-0)',
        '1': 'var(--spacing-1)',
        '2': 'var(--spacing-2)',
        '4': 'var(--spacing-4)',
        '6': 'var(--spacing-6)',
        '8': 'var(--spacing-8)',
        '10': 'var(--spacing-10)',
        '12': 'var(--spacing-12)',
        '14': 'var(--spacing-14)',
        '16': 'var(--spacing-16)',
        '18': 'var(--spacing-18)',
        '20': 'var(--spacing-20)',
        '24': 'var(--spacing-24)',
        '28': 'var(--spacing-28)',
        '32': 'var(--spacing-32)',
        '36': 'var(--spacing-36)',
        '40': 'var(--spacing-40)',
        '44': 'var(--spacing-44)',
        '48': 'var(--spacing-48)',
        '56': 'var(--spacing-56)',
        '64': 'var(--spacing-64)',
        '72': 'var(--spacing-72)',
        '80': 'var(--spacing-80)',
        '96': 'var(--spacing-96)',
        'max': 'var(--spacing-max)',
      },
      gap: {
        '1': 'var(--gap-1)',
        '2': 'var(--gap-2)',
        '3': 'var(--gap-3)',
        '4': 'var(--gap-4)',
        '5': 'var(--gap-5)',
        '6': 'var(--gap-6)',
        '7': 'var(--gap-7)',
        '8': 'var(--gap-8)',
        '9': 'var(--gap-9)',
        '10': 'var(--gap-10)',
        '11': 'var(--gap-11)',
        '12': 'var(--gap-12)',
      },
      padding: {
        '1': 'var(--padding-1)',
        '2': 'var(--padding-2)',
        '3': 'var(--padding-3)',
        '4': 'var(--padding-4)',
        '5': 'var(--padding-5)',
        '6': 'var(--padding-6)',
        '7': 'var(--padding-7)',
        '8': 'var(--padding-8)',
        '9': 'var(--padding-9)',
        '10': 'var(--padding-10)',
      },
      height: {
        '1': 'var(--size-height-1)',
        '2': 'var(--size-height-2)',
        '3': 'var(--size-height-3)',
        '4': 'var(--size-height-4)',
        '5': 'var(--size-height-5)',
        '6': 'var(--size-height-6)',
        '7': 'var(--size-height-7)',
        '8': 'var(--size-height-8)',
        '9': 'var(--size-height-9)',
        '10': 'var(--size-height-10)',
        '11': 'var(--size-height-11)',
      },
      borderRadius: {
        'xsmall': 'var(--radius-xsmall)',
        'small': 'var(--radius-small)',
        'medium': 'var(--radius-medium)',
        'large': 'var(--radius-large)',
        'xlarge': 'var(--radius-xlarge)',
        'max': 'var(--radius-max)',
      },
      boxShadow: {
        '1': 'var(--box-shadow-1)',
        '2': 'var(--box-shadow-2)',
        '3': 'var(--box-shadow-3)',
      },
      colors: {
        action: {
          white: 'var(--color-action-white)',
          selected: 'var(--color-action-selected)',
          primary: 'var(--color-action-primary)',
          'primary-hover': 'var(--color-action-primary-hover)',
          'primary-pressed': 'var(--color-action-primary-pressed)',
          secondary: 'var(--color-action-secondary)',
          'secondary-hover': 'var(--color-action-secondary-hover)',
          'secondary-pressed': 'var(--color-action-secondary-pressed)',
          disabled: 'var(--color-action-disabled)',
        },
        button: {
          'primary-fill': 'var(--color-button-primary-fill)',
          'primary-fill-hover': 'var(--color-button-primary-fill-hover)',
          'primary-fill-pressed': 'var(--color-button-primary-fill-pressed)',
          'secondary-fill': 'var(--color-button-secondary-fill)',
          'secondary-fill-hover': 'var(--color-button-secondary-fill-hover)',
          'secondary-fill-pressed': 'var(--color-button-secondary-fill-pressed)',
          'secondary-border': 'var(--color-button-secondary-border)',
          'tertiary-fill': 'var(--color-button-tertiary-fill)',
          'tertiary-fill-hover': 'var(--color-button-tertiary-fill-hover)',
          'tertiary-fill-pressed': 'var(--color-button-tertiary-fill-pressed)',
          'tertiary-fill-border': 'var(--color-button-tertiary-fill-border)',
          'text-fill': 'var(--color-button-text-fill)',
          'text-fill-hover': 'var(--color-button-text-fill-hover)',
          'text-fill-pressed': 'var(--color-button-text-fill-pressed)',
          'text-disabled': 'var(--color-button-text-disabled)',
          'disabled-fill': 'var(--color-button-disabled-fill)',
          'text-inverted-fill': 'var(--color-button-text-inverted-fill)',
          'text-inverted-hover': 'var(--color-button-text-inverted-hover)',
          'text-inverted-pressed': 'var(--color-button-text-inverted-pressed)',
          'text-inverted-disabled': 'var(--color-button-text-inverted-disabled)',
        },
        background: {
          white: 'var(--color-background-white)',
          gray: 'var(--color-background-gray)',
          inverted: 'var(--color-background-inverted)',
          dim: 'var(--color-background-dim)',
          'dim-inverted': 'var(--color-background-dim-inverted)',
        },
        text: {
          bolder: 'var(--color-text-bolder)',
          basic: 'var(--color-text-basic)',
          subtle: 'var(--color-text-subtle)',
          disabled: 'var(--color-text-disabled)',
          'disabled-on': 'var(--color-text-disabled-on)',
          'basic-inverted': 'var(--color-text-basic-inverted)',
          'disabled-inverted': 'var(--color-text-disabled-inverted)',
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          point: 'var(--color-text-point)',
          danger: 'var(--color-text-danger)',
          warning: 'var(--color-text-warning)',
          success: 'var(--color-text-success)',
          information: 'var(--color-text-information)',
        },
        element: {
          white: 'var(--color-element-white)',
          primary: 'var(--color-element-primary)',
          'primary-lighter': 'var(--color-element-primary-lighter)',
          secondary: 'var(--color-element-secondary)',
          'secondary-lighter': 'var(--color-element-secondary-lighter)',
          danger: 'var(--color-element-danger)',
          'danger-lighter': 'var(--color-element-danger-lighter)',
          warning: 'var(--color-element-warning)',
          'warning-lighter': 'var(--color-element-warning-lighter)',
          success: 'var(--color-element-success)',
          'success-lighter': 'var(--color-element-success-lighter)',
          information: 'var(--color-element-information)',
          'information-lighter': 'var(--color-element-information-lighter)',
          gray: 'var(--color-element-gray)',
          'gray-lighter': 'var(--color-element-gray-lighter)',
          disabled: 'var(--color-element-disabled)',
        },
        border: {
          'gray-light': 'var(--color-border-gray-light)',
          gray: 'var(--color-border-gray)',
          'gray-dark': 'var(--color-border-gray-dark)',
          inverted: 'var(--color-border-inverted)',
          disabled: 'var(--color-border-disabled)',
          'primary-light': 'var(--color-border-primary-light)',
          primary: 'var(--color-border-primary)',
          'primary-dark': 'var(--color-border-primary-dark)',
          'secondary-light': 'var(--color-border-secondary-light)',
          secondary: 'var(--color-border-secondary)',
          'danger-light': 'var(--color-border-danger-light)',
          danger: 'var(--color-border-danger)',
          'warning-light': 'var(--color-border-warning-light)',
          warning: 'var(--color-border-warning)',
          'success-light': 'var(--color-border-success-light)',
          success: 'var(--color-border-success)',
          'information-light': 'var(--color-border-information-light)',
          information: 'var(--color-border-information)',
        },
        surface: {
          white: 'var(--color-surface-white)',
          inverted: 'var(--color-surface-inverted)',
          gray: 'var(--color-surface-gray)',
        },
        input: {
          surface: 'var(--color-input-surface)',
          'surface-disabled': 'var(--color-input-surface-disabled)',
          border: 'var(--color-input-border)',
          'border-active': 'var(--color-input-border-active)',
          'border-error': 'var(--color-input-border-error)',
          'border-disabled': 'var(--color-input-border-disabled)',
        },
        icon: {
          inverted: 'var(--color-icon-inverted)',
          basic: 'var(--color-icon-basic)',
          primary: 'var(--color-icon-primary)',
          secondary: 'var(--color-icon-secondary)',
          disabled: 'var(--color-icon-disabled)',
          'disabled-on': 'var(--color-icon-disabled-on)',
          'disabled-inverted': 'var(--color-icon-disabled-inverted)',
          point: 'var(--color-icon-point)',
          danger: 'var(--color-icon-danger)',
          warning: 'var(--color-icon-warning)',
          success: 'var(--color-icon-success)',
          information: 'var(--color-icon-information)',
        },
        primary: {
          50: 'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
          950: 'var(--color-primary-950)',
        },
        secondary: {
          50: 'var(--color-secondary-50)',
          100: 'var(--color-secondary-100)',
          200: 'var(--color-secondary-200)',
          300: 'var(--color-secondary-300)',
          400: 'var(--color-secondary-400)',
          500: 'var(--color-secondary-500)',
          600: 'var(--color-secondary-600)',
          700: 'var(--color-secondary-700)',
          800: 'var(--color-secondary-800)',
          900: 'var(--color-secondary-900)',
          950: 'var(--color-secondary-950)',
        },
        gray: {
          0: 'var(--color-gray-0)',
          50: 'var(--color-gray-50)',
          100: 'var(--color-gray-100)',
          200: 'var(--color-gray-200)',
          300: 'var(--color-gray-300)',
          400: 'var(--color-gray-400)',
          500: 'var(--color-gray-500)',
          600: 'var(--color-gray-600)',
          700: 'var(--color-gray-700)',
          800: 'var(--color-gray-800)',
          900: 'var(--color-gray-900)',
          950: 'var(--color-gray-950)',
          1000: 'var(--color-gray-1000)',
        },
        red: {
          50: 'var(--color-red-50)',
          100: 'var(--color-red-100)',
          200: 'var(--color-red-200)',
          300: 'var(--color-red-300)',
          400: 'var(--color-red-400)',
          500: 'var(--color-red-500)',
          600: 'var(--color-red-600)',
          700: 'var(--color-red-700)',
          800: 'var(--color-red-800)',
          900: 'var(--color-red-900)',
          950: 'var(--color-red-950)',
        },
        yellow: {
          50: 'var(--color-yellow-50)',
          100: 'var(--color-yellow-100)',
          200: 'var(--color-yellow-200)',
          300: 'var(--color-yellow-300)',
          400: 'var(--color-yellow-400)',
          500: 'var(--color-yellow-500)',
          600: 'var(--color-yellow-600)',
          700: 'var(--color-yellow-700)',
          800: 'var(--color-yellow-800)',
          900: 'var(--color-yellow-900)',
          950: 'var(--color-yellow-950)',
        },
        green: {
          50: 'var(--color-green-50)',
          100: 'var(--color-green-100)',
          200: 'var(--color-green-200)',
          300: 'var(--color-green-300)',
          400: 'var(--color-green-400)',
          500: 'var(--color-green-500)',
          600: 'var(--color-green-600)',
          700: 'var(--color-green-700)',
          800: 'var(--color-green-800)',
          900: 'var(--color-green-900)',
          950: 'var(--color-green-950)',
        },
        blue: {
          50: 'var(--color-blue-50)',
          100: 'var(--color-blue-100)',
          200: 'var(--color-blue-200)',
          300: 'var(--color-blue-300)',
          400: 'var(--color-blue-400)',
          500: 'var(--color-blue-500)',
          600: 'var(--color-blue-600)',
          700: 'var(--color-blue-700)',
          800: 'var(--color-blue-800)',
          900: 'var(--color-blue-900)',
          950: 'var(--color-blue-950)',
        },
        alpha: {
          black100: 'var(--color-alpha-black100)',
          black75: 'var(--color-alpha-black75)',
          black50: 'var(--color-alpha-black50)',
          black25: 'var(--color-alpha-black25)',
          black10: 'var(--color-alpha-black10)',
          black0: 'var(--color-alpha-black0)',
          white100: 'var(--color-alpha-white100)',
          white75: 'var(--color-alpha-white75)',
          white50: 'var(--color-alpha-white50)',
          white25: 'var(--color-alpha-white25)',
          white10: 'var(--color-alpha-white10)',
          white0: 'var(--color-alpha-white0)',
        }
      }
    },
  },
  plugins: [],
}
